/**
 * The app's icon set: Material Design Icons path data, imported one by one
 * so only the glyphs used here reach the bundle (no icon font to download).
 * Semantic names keep call sites independent of the icon library.
 */
import {
  mdiAccountOutline,
  mdiAirplane,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiAllInclusive,
  mdiArrowBottomLeft,
  mdiArrowDown,
  mdiArrowRight,
  mdiArrowTopRight,
  mdiArrowUp,
  mdiAutoFix,
  mdiBackspaceOutline,
  mdiBank,
  mdiBankOutline,
  mdiBellOutline,
  mdiBookOpenVariant,
  mdiBriefcase,
  mdiBriefcaseOutline,
  mdiBus,
  mdiCalendarBlankOutline,
  mdiCalendarRange,
  mdiCameraOutline,
  mdiCar,
  mdiCardAccountDetailsOutline,
  mdiCart,
  mdiCashMultiple,
  mdiCellphone,
  mdiClockOutline,
  mdiChartBar,
  mdiChartDonut,
  mdiChartTimelineVariant,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckDecagramOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiClipboardCheckOutline,
  mdiClose,
  mdiCloudOffOutline,
  mdiCoffee,
  mdiCog,
  mdiCogOutline,
  mdiContentCopy,
  mdiContentPaste,
  mdiCreation,
  mdiCreationOutline,
  mdiCreditCard,
  mdiCreditCardOutline,
  mdiCreditCardSettingsOutline,
  mdiCurrencySign,
  mdiDatabaseOutline,
  mdiDownloadOutline,
  mdiDumbbell,
  mdiEmailAlertOutline,
  mdiEmailOutline,
  mdiExportVariant,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileDelimitedOutline,
  mdiFileDocumentOutline,
  mdiFilter,
  mdiFormTextboxPassword,
  mdiGamepadVariant,
  mdiGasStation,
  mdiGift,
  mdiHandCoinOutline,
  mdiHeart,
  mdiHelpCircleOutline,
  mdiHome,
  mdiHomeOutline,
  mdiImageOutline,
  mdiInboxOutline,
  mdiInformationOutline,
  mdiLightbulbOutline,
  mdiLightningBolt,
  mdiLineScan,
  mdiLockOutline,
  mdiLogout,
  mdiMagnify,
  mdiMagnifyClose,
  mdiMedicalBag,
  mdiMessageTextOutline,
  mdiMinusCircleOutline,
  mdiMovieOpen,
  mdiMusicNote,
  mdiNoteTextOutline,
  mdiPaw,
  mdiPencilOutline,
  mdiPiggyBank,
  mdiPiggyBankOutline,
  mdiPlus,
  mdiPlusCircleOutline,
  mdiPound,
  mdiPrinterOutline,
  mdiQrcode,
  mdiReceiptText,
  mdiReceiptTextOutline,
  mdiRefresh,
  mdiSchool,
  mdiShape,
  mdiShapeOutline,
  mdiShieldCheckOutline,
  mdiShopping,
  mdiSilverwareForkKnife,
  mdiSquareEditOutline,
  mdiStorefrontOutline,
  mdiSwapHorizontal,
  mdiSwapVertical,
  mdiTableLarge,
  mdiText,
  mdiThemeLightDark,
  mdiTrashCanOutline,
  mdiTrophyOutline,
  mdiTshirtCrew,
  mdiTune,
  mdiWallet,
  mdiWalletOutline,
  mdiWater,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiWifi,
  mdiHomeVariant,
} from '@mdi/js';
import type { CSSProperties } from 'react';

const ICONS = {
  // navigation
  home: mdiHomeOutline,
  homeActive: mdiHome,
  expenses: mdiReceiptTextOutline,
  expensesActive: mdiReceiptText,
  income: mdiPiggyBankOutline,
  incomeActive: mdiPiggyBank,
  reports: mdiChartBar,
  settings: mdiCogOutline,
  settingsActive: mdiCog,
  back: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  chevronLeft: mdiChevronLeft,
  chevronDown: mdiChevronDown,
  close: mdiClose,
  // actions
  add: mdiPlus,
  edit: mdiPencilOutline,
  delete: mdiTrashCanOutline,
  export: mdiExportVariant,
  filter: mdiTune,
  filterActive: mdiFilter,
  sort: mdiSwapVertical,
  search: mdiMagnify,
  searchOff: mdiMagnifyClose,
  refresh: mdiRefresh,
  copy: mdiContentCopy,
  paste: mdiContentPaste,
  backspace: mdiBackspaceOutline,
  send: mdiArrowUp,
  newChat: mdiSquareEditOutline,
  arrowForward: mdiArrowRight,
  print: mdiPrinterOutline,
  download: mdiDownloadOutline,
  // money
  assistant: mdiCreationOutline,
  assistantSolid: mdiCreation,
  bank: mdiBankOutline,
  bankSolid: mdiBank,
  budget: mdiChartDonut,
  expense: mdiMinusCircleOutline,
  incomeAdd: mdiPlusCircleOutline,
  moneyIn: mdiArrowBottomLeft,
  moneyOut: mdiArrowTopRight,
  up: mdiArrowUp,
  down: mdiArrowDown,
  transfer: mdiSwapHorizontal,
  swapVertical: mdiSwapVertical,
  cash: mdiCashMultiple,
  upi: mdiQrcode,
  card: mdiCreditCardOutline,
  lend: mdiHandCoinOutline,
  cardSolid: mdiCreditCard,
  walletOutline: mdiWalletOutline,
  wallet: mdiWallet,
  paymentMethod: mdiCreditCardSettingsOutline,
  category: mdiShapeOutline,
  currency: mdiCurrencySign,
  trophy: mdiTrophyOutline,
  insights: mdiChartTimelineVariant,
  allInclusive: mdiAllInclusive,
  tag: mdiPound,
  // fields
  email: mdiEmailOutline,
  lock: mdiLockOutline,
  person: mdiAccountOutline,
  eye: mdiEyeOutline,
  eyeOff: mdiEyeOffOutline,
  store: mdiStorefrontOutline,
  text: mdiText,
  notes: mdiNoteTextOutline,
  work: mdiBriefcaseOutline,
  calendar: mdiCalendarBlankOutline,
  calendarRange: mdiCalendarRange,
  time: mdiClockOutline,
  bell: mdiBellOutline,
  badge: mdiCardAccountDetailsOutline,
  password: mdiFormTextboxPassword,
  // status
  check: mdiCheck,
  checkCircle: mdiCheckCircle,
  verified: mdiCheckDecagramOutline,
  shield: mdiShieldCheckOutline,
  info: mdiInformationOutline,
  warning: mdiAlertOutline,
  error: mdiAlertCircleOutline,
  help: mdiHelpCircleOutline,
  factCheck: mdiClipboardCheckOutline,
  lightbulb: mdiLightbulbOutline,
  mailUnread: mdiEmailAlertOutline,
  inbox: mdiInboxOutline,
  offline: mdiCloudOffOutline,
  database: mdiDatabaseOutline,
  // features
  scan: mdiLineScan,
  camera: mdiCameraOutline,
  gallery: mdiImageOutline,
  sms: mdiMessageTextOutline,
  autoFix: mdiAutoFix,
  document: mdiFileDocumentOutline,
  csv: mdiFileDelimitedOutline,
  table: mdiTableLarge,
  logout: mdiLogout,
  themeAuto: mdiThemeLightDark,
  themeLight: mdiWhiteBalanceSunny,
  themeDark: mdiWeatherNight,
} as const;

/** Glyphs for the names stored in `categories.icon` (Flutter's Material names). */
const CATEGORY_ICONS: Record<string, string> = {
  restaurant: mdiSilverwareForkKnife,
  directions_bus: mdiBus,
  shopping_bag: mdiShopping,
  receipt_long: mdiReceiptText,
  movie: mdiMovieOpen,
  favorite: mdiHeart,
  flight: mdiAirplane,
  school: mdiSchool,
  category: mdiShape,
  home: mdiHomeVariant,
  pets: mdiPaw,
  fitness_center: mdiDumbbell,
  local_cafe: mdiCoffee,
  local_grocery_store: mdiCart,
  phone_android: mdiCellphone,
  wifi: mdiWifi,
  bolt: mdiLightningBolt,
  water_drop: mdiWater,
  card_giftcard: mdiGift,
  savings: mdiPiggyBank,
  work: mdiBriefcase,
  directions_car: mdiCar,
  local_gas_station: mdiGasStation,
  medical_services: mdiMedicalBag,
  sports_esports: mdiGamepadVariant,
  music_note: mdiMusicNote,
  book: mdiBookOpenVariant,
  checkroom: mdiTshirtCrew,
};

export type IconName = keyof typeof ICONS;

type IconProps = {
  name: IconName;
  size?: number;
  color?: string;
  className?: string;
  style?: CSSProperties;
  title?: string;
};

function Svg({ path, size = 20, color, className, style, title }: Omit<IconProps, 'name'> & { path: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className={className}
      style={{ flex: 'none', ...style }}
      aria-hidden={title ? undefined : true}
      role={title ? 'img' : undefined}
      focusable="false"
    >
      {title ? <title>{title}</title> : null}
      <path d={path} fill={color ?? 'currentColor'} />
    </svg>
  );
}

export function Icon({ name, ...rest }: IconProps) {
  return <Svg path={ICONS[name]} {...rest} />;
}

export function CategoryGlyph({ icon, ...rest }: Omit<IconProps, 'name'> & { icon: string | null | undefined }) {
  return <Svg path={CATEGORY_ICONS[icon ?? ''] ?? mdiShape} {...rest} />;
}
